services:
  postgres_versioned:
    image: postgres:16.1-alpine
    container_name: graphql_demo
    environment:
      POSTGRES_DB: graphql_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/db_data/volume:/var/lib/postgresql/data
